apiVersion: apps/v1 
kind: Deployment
metadata:
  name: reto2_api
  labels: 
     app: api

spec:
  replicas: 1 
  selector:
    matchLabels:
      app: api

  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: guillermocarrion/reto2_api:01
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1